<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="/css/role.css">
    <link rel="shortcut icon" href="/img/sql.png"/>
    <title>Выбрать роль</title>
</head>
<body>
    <section>
        <a class="back" href="/"><i class="fa-solid fa-arrow-left"></i> Вернуться</a>
        <h2>Выберите роль</h2>
        <div class="type-group">
            <a class="action task-student" href="/student">
                <i class="fa-solid fa-arrow-right"></i>
                <span>Ученик</span>
                <small>Выполнение персональных заданий, выданных учителем.</small>
            </a>
            <a class="action task-teacher" href="/teacher">
                <i class="fa-solid fa-arrow-right"></i>
                <span>Учитель</span>
                <small>Составление персональных задания для учеников.</small>
            </a>
        </div>
    </section>
</body>
</html>